name: CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Run Tests
        run:  |
          source venv/bin/activate
          pytest
